name: cloudinary_service
description: "Cloudinary service wrapper for Deliverak"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.5
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  cloudinary: ^1.2.2
  cloudinary_url_gen: ^1.8.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
