name: customer
description: "Deliverak Customer App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  go_router: ^14.6.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.5
  cloudinary_flutter: ^1.3.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.4
  core:
    path: ../../packages/core
  firebase_services:
    path: ../../packages/firebase_services
  cloudinary_service:
    path: ../../packages/cloudinary_service
  repositories:
    path: ../../packages/repositories
  providers:
    path: ../../packages/providers
  ui_kit:
    path: ../../packages/ui_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
